-- Run this once in the Supabase SQL editor (project uvzwhhwzelaelfhfkvdb)
-- Tracks completion + notes for the recurring Monthly Posting Schedule under
-- Marketing. The schedule template itself (weeks/days/tasks) is fixed in the
-- app, not stored here -- this table only tracks per-month "did we do this /
-- notes about it" state, keyed by month so it naturally resets each month.

create table if not exists marketing_posting_log (
  id bigint generated by default as identity primary key,
  month text not null,
  item_key text not null,
  done boolean not null default false,
  comment text,
  updated_at timestamptz not null default now(),
  unique (month, item_key)
);

create index if not exists idx_marketing_posting_log_month on marketing_posting_log(month);

alter table marketing_posting_log enable row level security;

drop policy if exists "token_can_read" on marketing_posting_log;
create policy "token_can_read" on marketing_posting_log for select to anon, authenticated using (true);

drop policy if exists "token_can_insert" on marketing_posting_log;
create policy "token_can_insert" on marketing_posting_log for insert to anon, authenticated with check (true);

drop policy if exists "token_can_update" on marketing_posting_log;
create policy "token_can_update" on marketing_posting_log for update to anon, authenticated using (true);
