-- Run this once in the Supabase SQL editor (project uvzwhhwzelaelfhfkvdb)
-- Stores reconciliation checkpoints for Financial Overview tabs. Purely a visual marker --
-- clicking "Mark Reconciled" records a timestamp and the UI grays out everything dated on or
-- before it, but no totals change and no records are ever deleted or hidden.

create table if not exists financial_reconciliations (
  id bigint generated by default as identity primary key,
  scope text not null,
  reconciled_at timestamptz not null default now(),
  reconciled_by text
);

create index if not exists idx_financial_reconciliations_scope
  on financial_reconciliations(scope, reconciled_at desc);
