-- Run this once in the Supabase SQL editor.
-- Single-row settings for the Volunteer Interest Form's "Email Volunteer"
-- thank-you email (subject line + header title), editable from Admin ->
-- Operational Budgets alongside each area's Volunteer Welcome Message.
-- Both fields support a {{first_name}} placeholder, substituted with the
-- applicant's first name when the email is built.

create table if not exists volunteer_interest_settings (
  id           bigint generated by default as identity primary key,
  subject      text,
  header_title text,
  updated_at   timestamptz not null default now()
);

alter table volunteer_interest_settings enable row level security;

create policy "public read"   on volunteer_interest_settings for select using (true);
create policy "public insert" on volunteer_interest_settings for insert with check (true);
create policy "public update" on volunteer_interest_settings for update using (true);
create policy "public delete" on volunteer_interest_settings for delete using (true);
