-- Run this once in the Supabase SQL editor (project uvzwhhwzelaelfhfkvdb)
-- Adds the donor acknowledgment (thank-you letter + envelope) document system:
-- new fields on donations/donors, plus template and org-settings config tables.

-- === donations: acknowledgment fields ===
alter table donations
  add column if not exists acknowledgment_type text,
  add column if not exists membership_level text,
  add column if not exists membership_start_date date,
  add column if not exists membership_expiration_date date,
  add column if not exists event_name text,
  add column if not exists sponsorship_level text,
  add column if not exists brick_inscription text,
  add column if not exists memorial_recipient text,
  add column if not exists honoree_name text,
  add column if not exists in_kind_description text,
  add column if not exists in_kind_value numeric,
  add column if not exists tax_deductible_amount numeric,
  add column if not exists goods_services_value numeric,
  add column if not exists check_number text,
  add column if not exists signer_name text,
  add column if not exists signer_title text,
  add column if not exists letter_greeting_override text,
  add column if not exists acknowledgment_status text not null default 'ready_to_generate',
  add column if not exists letter_drive_url text,
  add column if not exists envelope_drive_url text,
  add column if not exists letter_drive_file_id text,
  add column if not exists envelope_drive_file_id text,
  add column if not exists template_used text,
  add column if not exists document_version integer not null default 0,
  add column if not exists date_generated timestamptz,
  add column if not exists date_printed timestamptz,
  add column if not exists date_mailed timestamptz,
  add column if not exists generated_by text,
  add column if not exists generation_error text,
  add column if not exists preferred_ack_method text not null default 'Printed Letter';

-- === donors: greeting + structured mailing address ===
alter table donors
  add column if not exists preferred_letter_greeting text,
  add column if not exists joint_donor_name text,
  add column if not exists mailing_address_line1 text,
  add column if not exists mailing_address_line2 text,
  add column if not exists mailing_city text,
  add column if not exists mailing_state text,
  add column if not exists mailing_zip text;

-- === acknowledgment_templates: one row per Acknowledgment Type ===
create table if not exists acknowledgment_templates (
  id bigint generated by default as identity primary key,
  acknowledgment_type text not null unique,
  template_name text,
  letter_storage_path text,
  envelope_storage_path text,
  active boolean not null default true,
  default_signer_name text,
  default_signer_title text,
  required_fields jsonb default '[]'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by text
);

-- === acknowledgment_settings: single org-wide settings row ===
create table if not exists acknowledgment_settings (
  id bigint generated by default as identity primary key,
  org_legal_name text,
  ein text,
  return_address_line1 text,
  return_address_line2 text,
  return_address_city text,
  return_address_state text,
  return_address_zip text,
  tax_ack_language text,
  goods_services_language text,
  in_kind_language text,
  envelope_size text not null default '#10',
  shared_drive_id text,
  root_folder_name text not null default 'North Star House',
  updated_at timestamptz not null default now(),
  updated_by text
);

insert into acknowledgment_settings (org_legal_name, root_folder_name)
select 'North Star Historic Conservancy', 'North Star House'
where not exists (select 1 from acknowledgment_settings);

-- Seed template rows for the 5 acknowledgment types with real templates today.
-- letter_storage_path values point at the "acknowledgment-templates" Storage bucket
-- (uploaded separately) -- update paths there if file names change.
insert into acknowledgment_templates (acknowledgment_type, template_name, letter_storage_path, envelope_storage_path, default_signer_name, default_signer_title)
values
  ('Membership', 'Membership Thank You Template', 'membership.docx', 'envelope-standard.docx', 'Ken Underwood', 'President'),
  ('Brick Purchase', 'Bricks Template', 'bricks.docx', 'envelope-standard.docx', 'Ken Underwood', 'President'),
  ('In-Kind Donation', 'In-Kind Thank You Letter Template', 'in-kind.docx', 'envelope-standard.docx', 'Ken Underwood', 'President'),
  ('Memorial Donation', 'Tribute Thank You Letter Template', 'tribute.docx', 'envelope-standard.docx', 'Ken Underwood', 'President'),
  ('Honorary Donation', 'Tribute Thank You Letter Template', 'tribute.docx', 'envelope-standard.docx', 'Ken Underwood', 'President'),
  ('General Donation', 'Restricted Thank You Letter Template', 'restricted.docx', 'envelope-standard.docx', 'Ken Underwood', 'President')
on conflict (acknowledgment_type) do nothing;

-- Event Donation, Sponsorship, and Other are intentionally left without a template row --
-- the admin "Acknowledgment Templates" page will show them as "No template" until
-- someone uploads one; the app must not error, only mark those as Needs Review.
