-- Run this once in the Supabase SQL editor
-- Adds a table for guest/attendee feedback on events, shown in the
-- "Reviews & Feedback" tab of the Events admin page.

create table if not exists "Event Feedback" (
  id bigint generated by default as identity primary key,
  event_name text,
  source text,
  name text,
  feedback text,
  date date,
  created_at timestamptz not null default now()
);
