-- Run this once in the Supabase SQL editor.
-- Backs the redesigned "Events" tab on the Event Overviews page: a card per
-- event (flyer image + date), split into Upcoming/Past sections, that opens
-- into a per-event dashboard (ticket sales, marketing checklist, expenses).
-- event_name is matched (case-insensitively, client-side) against the same
-- free-text event names already used in "Op Earnings"/"Op Budget"/"In-House
-- Events" -- this table only adds the extra per-event metadata those tables
-- don't have (flyer image, marketing checklist).

create table if not exists event_overview_cards (
  id                      bigint generated by default as identity primary key,
  event_name              text not null unique,
  event_date              date,
  image_url               text,
  image_drive_file_id     text,
  image_drive_folder_url  text,
  checklist               jsonb not null default '[]'::jsonb,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);

alter table event_overview_cards enable row level security;

create policy "public read"   on event_overview_cards for select using (true);
create policy "public insert" on event_overview_cards for insert with check (true);
create policy "public update" on event_overview_cards for update using (true);
create policy "public delete" on event_overview_cards for delete using (true);
